### PR TITLE
Raycast mesh painting

### PR DESCRIPTION
**Pull request by alexjhetherington**
Dirty, unclean! You can set up a quick test scene just using 2 quads scaled up at an angle. Paint on the top one and you will see the effect when the ivy cascades down.

quads

### CODE REVIEW

**Comment by radiatoryang** [comment]
Sorry, totally forgot to look at this... pandemic, etc. And honestly I still can't really muster the energy to fire up Unity and merge it in properly yet. But I will definitely try to get this in sometime this year. 

Again, thanks for the PR and I appreciate it, it's not you it's me, etc.

**Comment by Thundros** [comment]
@radiatoryang for some reason when i merge the vines into one ( when i have painted say 2 vine assets ), it removes some of my mesh for some reason. PLEASE fix the export. I'm trying to let the ivy be "attached" to the object it was painted on in order to allow for things such as an ancient pillar that falls & rolls on the ground. I want the ivy to roll WITH it. Don't make me beg more than I already have to!!!!!!!!

**Comment by Thundros** [comment]
@radiatoryang ?????

**Comment by Thundros** [comment]
...........

**Comment by radiatoryang** [comment]
@Thundros Hi, all these repetitive messages are really inappropriate. If you want to file a bug, create a new issue and include screenshots + how to reproduce the bug. Do not spam someone else's pull request. Please behave better.

**Comment by radiatoryang** [comment]
Working on this now, trying to figure out UX / UI for it, will be implemented in next tagged release on master branch (v1.2.3)

**Pull request merged**
